In [3]:
import numpy as np
import os
import struct
import sys
import image_utils as iu

training_image_file= "train-images.idx3-ubyte"
training_label_file = "train-labels.idx1-ubyte"
test_image_file = "t10k-images.idx3-ubyte"
test_label_file = "t10k-labels.idx1-ubyte"

image_data_folder = "data"

In [4]:
def one_hot_encode(np_1d_arr):
    return np.eye(np.max(np_1d_arr) + 1)[np_1d_arr.flatten()]

In [5]:
# Load the training images and labels:
training_data = iu.load_image_file(training_image_file)
training_labels = iu.load_labels_file(training_label_file)

Total images in file: 60000
Total labels in file: 60000


In [6]:
# Load the test images and labels:
test_data = iu.load_image_file(test_image_file)
test_labels = iu.load_labels_file(test_label_file)

Total images in file: 10000
Total labels in file: 10000


In [7]:
# Create a one-hot-encoding from the labels:
test_labels = one_hot_encode(test_labels)
training_labels = one_hot_encode(training_labels)

print("test_labels shape: {}".format(test_labels.shape))
print("training_labels shape: {}".format(training_labels.shape))

test_labels shape: (10000, 10)
training_labels shape: (60000, 10)


In [100]:
# normalise the training and test img_data to be in the range [-1, 1]
training_data_norm = (training_data - 128)/128
test_data_norm = (test_data - 128)/128

In [123]:
# Set neural nets hyperparameters:
learning_rate = 0.005
iterations = 5

input_layer_size = 28*28 # Number of pixels per image
hidden_layer_size = 64
output_layer_size  = 10



In [124]:
print(weights_0_1.shape)
print(weights_1_2.shape)
# layer_test = training_data[0: 1]
# layer_1 = layer_test.dot(weights_0_1)          # (1 x 64)
# layer_2 = softmax(layer_1.dot(weights_1_2))
# prob_to_class(layer_2)

(784, 64)
(64, 10)


In [125]:
# Define the activation functions and their derivatives:
def relu(x):
    return (x >= 0) * x

def relu_deriv(x):
    return x >= 0

def softmax(np_arr):
    return np.exp(np_arr) / np.sum(np.exp(np_arr))

def prob_to_class(np_arr):
    return (np_arr == np.max(np_arr))*1

In [128]:
weights_0_1 = 0.2 * np.random.random((input_layer_size, hidden_layer_size)) - 0.1  # (784 x 64)
weights_1_2 = 0.2 * np.random.random((hidden_layer_size, output_layer_size)) - 0.1 # (64 x 10)

for iter in range(iterations):
    iter_error = 0
    test_error = 0
    correct_cnt = 0
    correct_test_cnt = 0
    for img_index in range(len(training_data_norm)):
        
        label = training_labels[img_index: img_index + 1] # (1 x 10)
        layer_0 = training_data_norm[img_index: img_index + 1] # (1 x 784)
        layer_1 = relu(layer_0.dot(weights_0_1))          # (1 x 64)
        layer_2 = layer_1.dot(weights_1_2)                # (1 x 10)
         
        iter_error += np.sum((layer_2 - label)**2)
        correct_cnt += np.argmax(layer_2) == np.argmax(label)
        
        delta_2 = (layer_2 - label)                     # (1 x 10)
        delta_1 = delta_2.dot(weights_1_2.T)*relu_deriv(layer_1) # (1 x 64)

        weights_1_2 -= learning_rate * layer_1.T.dot(delta_2)
        weights_0_1 -= learning_rate * layer_0.T.dot(delta_1)

        
#         if img_index % 6000 == 0:
#             print("delta_2: {}".format(delta_2))
#             print("delta_1: {}".format(delta_1))
    if iter % 1 == 0:    
        # estimate the test accuracy:
        for j in range(len(test_data_norm)):
        
            test_label = test_labels[j: j + 1] # (1 x 10)
            layer_0_test = test_data_norm[j: j + 1] # (1 x 784)
            layer_1_test = relu(layer_0_test.dot(weights_0_1))          # (1 x 64)
            layer_2_test = layer_1_test.dot(weights_1_2)                # (1 x 10)
         
            test_error += np.sum((layer_2_test - test_label)**2)
            correct_test_cnt += np.argmax(layer_2_test) == np.argmax(test_label)
        
        print("Error: {}, Training Accuracy: {}, Test Accuracy: {}"
              .format(iter_error/len(training_data_norm), correct_cnt/len(training_data_norm), correct_test_cnt/len(test_data_norm)))

Error: 0.34789932575576965, Training Accuracy: 0.83885, Test Accuracy: 0.8482
Error: 0.30025935363558387, Training Accuracy: 0.86805, Test Accuracy: 0.8649
Error: 0.2936307011457737, Training Accuracy: 0.8724166666666666, Test Accuracy: 0.8612
Error: 0.29355294351526967, Training Accuracy: 0.8713, Test Accuracy: 0.8518
Error: 0.3067986295573586, Training Accuracy: 0.8625666666666667, Test Accuracy: 0.8404


In [34]:
training_data[0: 1].shape

(1, 784)

In [12]:
test2 = softmax(test)


In [102]:
len(training_data_norm)

60000

In [22]:
test2 = 


In [23]:
test2

array([0, 0, 0, 1])

In [19]:
True*1

1

In [87]:
np.argmax(test2)

3

In [41]:
def relu(x):
    return (x > 0) * x

In [42]:
test3

array([0, 0, 0, 1])

In [43]:
relu(np.array([-.3,1,2.-.4]))

array([-0. ,  1. ,  1.6])

In [45]:
tt = np.array([-3, 1, 2, -44])
relu(tt)

array([0, 1, 2, 0])

In [98]:
np.min(training_data)

0

In [99]:
np.max((training_data-128)/128)

0.9921875